### ISSUE TITLE
Server Crash - 1.7.10 - Ticking entity

### ISSUE THREAD

**Issue by Da-Spud** [FiskFille/AdvancedLightsabers#19]
I found out that throwing a Lightsaber at a nether portal is a bad idea, but now everytime i go into the nether even with an empty inventory the server will still crash..

CRASH REPORT BELOW

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 7/19/16 11:11 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at fiskfille.lightsabers.common.entity.EntityLightsaber.func_70184_a(EntityLightsaber.java:173)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(EntityThrowable.java:216)
	at fiskfille.lightsabers.common.entity.EntityLightsaber.func_70071_h_(EntityLightsaber.java:75)
	at net.minecraft.world.World.func_72866_a(World.java:2674)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:800)
	at net.minecraft.world.World.func_72870_g(World.java:2623)
	at net.minecraft.world.World.func_72939_s(World.java:2423)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at fiskfille.lightsabers.common.entity.EntityLightsaber.func_70184_a(EntityLightsaber.java:173)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(EntityThrowable.java:216)
	at fiskfille.lightsabers.common.entity.EntityLightsaber.func_70071_h_(EntityLightsaber.java:75)
	at net.minecraft.world.World.func_72866_a(World.java:2674)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:800)
	at net.minecraft.world.World.func_72870_g(World.java:2623)

-- Entity being ticked --
Details:
	Entity Type: al_Lightsaber (fiskfille.lightsabers.common.entity.EntityLightsaber)
	Entity ID: 50
	Entity Name: entity.al_Lightsaber.name
	Entity's Exact location: 703.00, 69.50, -39.00
	Entity's Block location: World: (703,69,-39), Chunk: (at 15,4,9 in 43,-3; contains blocks 688,0,-48 to 703,255,-33), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Entity's Momentum: 1.33, 0.04, -1.31
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2423)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633)

-- Affected level --
Details:
	Level name: DIM-1
	All players: 1 total; [GCEntityPlayerMP['Im_Hot_xx'/48, l='DIM-1', x=703.00, y=69.50, z=-39.00](Im_Hot_xx at 703.0,69.5,-39.0)]
	Chunk stats: ServerChunkCache: 241 Drop: 0
	Level seed: -2447315149683421488
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 17774395 game time, 20261 day time
	Level dimension: -1
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	KCauldron Version: pw.prok:KCauldron:1.7.10-1614.201 Official
	Plugins: WorldEdit, Essentials, EssentialsProtect, VoxelSniper, EssentialsChat, BanItem, ClearLag, EssentialsAntiBuild, LittlePets, PermissionsEx, SendPlugin, EssentialsSpawn, GriefPrevention, EssentialsKitManager
	Disabled Plugins: 
	Operating System: Windows Server 2008 R2 (amd64) version 6.1
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 429144704 bytes (409 MB) / 1918369792 bytes (1829 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -Xmx4096M -Xms256M -XX:MaxPermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 97
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 117 mods loaded, 108 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (KCauldron-1.7.10-1614.201.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (KCauldron-1.7.10-1614.201.jar) 
	UCHIJAAAA	kimagine{0.2} [KImagine] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-5} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{1.2.1} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	ThE-core{1.0.0.1} [Thaumic Energistics Core] (minecraft.jar) 
	UCHIJAAAA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.10.5+unknown-b0.git-unknown} [Malisis Core] (malisiscore-1.7.10-0.10.5.jar) 
	UCHIJAAAA	psychedelicraftcore{1.4} [Psychedelicraft Core] (minecraft.jar) 
	UCHIJAAAA	lightsabers{1.0.5} [Advanced Lightsabers Mod] (AdvancedLightsabers-1.7.10-1.0.5.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-5} [Applied Energistics 2] (appliedenergistics2-rv3-beta-5.jar) 
	UCHIJAAAA	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) 
	UCHIJAAAA	armourersWorkshop{1.7.10-0.39.4.105} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.39.4.105.jar) 
	UCHIJAAAA	plushieWrapper{0.0.0} [Plushie Wrapper] (Armourers-Workshop-1.7.10-0.39.4.105.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHIJAAAA	asielib{0.4.5} [asielib] (AsieLib-1.7.10-0.4.5.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHIJAAAA	betterrecords{@VERSION@} [Better Records] (BetterRecords-1.7.10-1.2.0.jar) 
	UCHIJAAAA	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1826-universal.jar) 
	UCHIJAAAA	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.3-112.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.2-240.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHIJAAAA	bookshelf{1.0.4.172} [Bookshelf] (Bookshelf-1.7.10-1.0.4.172.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.14} [BuildCraft] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.14} [BC Builders] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.14} [BC Transport] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.14} [BC Energy] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.14} [BC Silicon] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.14} [BC Robotics] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.14} [BC Factory] (buildcraft-7.1.14.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.9.4.10} [Chisel] (Chisel-2.9.4.10.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(21feb16).jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.2.1_1.7.10.jar) 
	UCHIJAAAA	props{2.2.1} [Decocraft] (Decocraft-2.2.1_1.7.10.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.441.jar) 
	UCHIJAAAA	Mekanism{9.0.3} [Mekanism] (Mekanism-1.7.10-9.0.3.277.jar) 
	UCHIJAAAA	DefenseTech{1.0.1} [DefenseTech] (DefenseTech-1.7.10-1.0.1.26.jar) 
	UCHIJAAAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJAAAA	eplus{4.0.0..73} [Enchanting Plus] (EnchantingPlus-1.7.10-4.0.0.74.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.31_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.31_beta.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.423_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.423_beta.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.38} [EnderStorage] (EnderStorage-1.7.10-1.4.7.38-universal.jar) 
	UCHIJAAAA	etfuturum{1.5.5} [Et Futurum] (Et Futurum-1.5.5.jar) 
	UCHIJAAAA	extracells{2.3.9} [Extra Cells 2] (ExtraCells-1.7.10-2.3.9b188.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
	UCHIJAAAA	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
	UCHIJAAAA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCHIJAAAA	ForbiddenMagic{1.7.10-0.562} [Forbidden Magic] (Forbidden Magic-1.7.10-0.562.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.441.jar) 
	UCHIJAAAA	HardcoreDarkness{1.7} [Hardcore Darkness] (HardcoreDarkness-MC1.7.10-1.7.jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJAAAA	InventoryPets{1.4.7.1} [Inventory Pets] (inventorypets-1.7.10-1.4.7.1-universal.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	jcanimation{1.2.4} [JCAnimationAPI] (JurassiCraft-1.4.5.jar) 
	UCHIJAAAA	llibrary{0.3.2-1.7.10} [LLibrary] (LLibrary-0.3.2-1.7.10.jar) 
	UCHIJAAAA	jurassicraft{1.4.5} [JurassiCraft] (JurassiCraft-1.4.5.jar) 
	UCHIJAAAA	magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops] (magicalcrops-1.7.10_0.1.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.4.3} [Malisis' Doors] (malisisdoors-1.7.10-1.4.3.jar) 
	UCHIJAAAA	MekanismGenerators{9.0.3} [MekanismGenerators] (MekanismGenerators-1.7.10-9.0.3.277.jar) 
	UCHIJAAAA	MekanismTools{9.0.3} [MekanismTools] (MekanismTools-1.7.10-9.0.3.277.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatMagicalCrops{1.0beta} [MFR Compat: MagicalCrops] (MineFactoryReloaded-CompatMagicalCrops.jar) 
	UCHIJAAAA	cfm{3.4.8} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8(1.7.10).jar) 
	UCHIJAAAA	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
	UCHIJAAAA	recipemod{0.2} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.2(1.7.10).jar) 
	UCHIJAAAA	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
	UCHIJAAAA	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) 
	UCHIJAAAA	psychedelicraft{1.5.2} [Psychedelicraft] (Psychedelicraft-1.5.2.jar) 
	UCHIJAAAA	RandomThings{2.1.7} [Random Things] (RandomThings-2.1.7.jar) 
	UCHIJAAAA	SGCraft{1.9.3} [Greg's SG Craft] (SGCraft-1.9.3-mc1.7.10.jar) 
	UCHIJAAAA	SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways] (Soul Shards- The Old Ways.jar) 
	UCHIJAAAA	statues{2.1.4} [Statues] (statues-1.7.10-2.1.4.jar) 
	UCHIJAAAA	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHIJAAAA	thaumicenergistics{1.0.0.5} [Thaumic Energistics] (thaumicenergistics-1.0.0.5.jar) 
	UCHIJAAAA	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) 
	UCHIJAAAA	IguanaTweaksTConstruct{1.7.10-2.1.6.163} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.6.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
	Class transformer null safety: all safe
	AE2 Version: beta rv3-beta-5 for Forge 10.13.4.1448
	CoFHCore: -[1.7.10]3.1.2-325
	ThermalFoundation: -[1.7.10]1.2.3-112
	ThermalExpansion: -[1.7.10]4.1.2-240
	MineFactoryReloaded: -[1.7.10]2.8.1-174
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.1-22
	ThermalDynamics: -[1.7.10]1.1.0-161
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.1.0 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.13B1 from extrautilities-1.2.12.jar).
                    It is a supported version, but that difference may lead to problems.
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-5.jar).
                    Ender IO was build against API version rv2 and my not work with newer version.
                 An unsupported base software is installed: 'kcauldron, cauldron, craftbukkit, mcpc'. This is NOT supported.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 56; [GCEntityPlayerMP['Im_Hot_xx'/48, l='DIM-1', x=703.00, y=69.50, z=-39.00](Im_Hot_xx at 703.0,69.5,-39.0)]
	Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Da-Spud** [comment]
I would also like to ask how can i stop the lightsabers in mid flight getting taken by clearlagg?

**Comment by 1n5aN1aC** [comment]
Happened to us too.

Except going back into the nether does not continue to crash the server for us.

**Comment by LemADEC** [comment]
Is this fixed  in 1.1?

**Comment by Cronosus** [comment]
still crashing with this in latest version 1.7.10
only way to stop crash is WE butcher or clearlagg
