### ISSUE TITLE
Accidental Scala dependency

### ISSUE THREAD

**Issue by FiskFille** [FiskFille/AdvancedLightsabers#36]
---- Minecraft Crash Report -------- Minecraft Crash Report ----// I just don't know what went wrong :(
Time: 9/9/17 8:29 PMDescription: Ticking entity
java.lang.NoClassDefFoundError: scala/util/Random at fiskfille.lightsabers.common.event.CommonEventHandler.onPlayerTick(CommonEventHandler.java:360) at cpw.mods.fml.common.eventhandler.ASMEventHandler_15_CommonEventHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic) at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) at cpw.mods.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:350) at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:353) at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63) at net.minecraft.world.World.func_72866_a(World.java:2070) at net.minecraft.world.World.func_72870_g(World.java:2034) at net.minecraft.world.World.func_72939_s(World.java:1887) at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006) at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) at net.minecraft.client.main.Main.main(SourceFile:148) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at info.mineshafter.GameStarter.main(GameStarter.java:33)Caused by: java.lang.ClassNotFoundException: scala.util.Random at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) at java.lang.ClassLoader.loadClass(Unknown Source) at java.lang.ClassLoader.loadClass(Unknown Source) ... 25 moreCaused by: java.lang.NullPointerException at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ... 27 more

A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- Head --Stacktrace: at fiskfille.lightsabers.common.event.CommonEventHandler.onPlayerTick(CommonEventHandler.java:360) at cpw.mods.fml.common.eventhandler.ASMEventHandler_15_CommonEventHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic) at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) at cpw.mods.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:350) at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:353) at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63) at net.minecraft.world.World.func_72866_a(World.java:2070) at net.minecraft.world.World.func_72870_g(World.java:2034)
-- Entity being ticked --Details: Entity Type: null (net.minecraft.client.entity.EntityClientPlayerMP) Entity ID: 109 Entity Name: Luke124816 Entity's Exact location: -1526.82, 65.62, 1327.75 Entity's Block location: World: (-1527,65,1327), Chunk: (at 9,4,15 in -96,82; contains blocks -1536,0,1312 to -1521,255,1327), Region: (-3,2; contains chunks -96,64 to -65,95, blocks -1536,0,1024 to -1025,255,1535) Entity's Momentum: 0.00, -0.08, 0.00Stacktrace: at net.minecraft.world.World.func_72939_s(World.java:1887)
-- Affected level --Details: Level name: MpServer All players: 1 total; [EntityClientPlayerMP['Luke124816'/109, l='MpServer', x=-1526.82, y=65.62, z=1327.75]] Chunk stats: MultiplayerChunkCache: 623, 623 Level seed: 0 Level generator: ID 01 - flat, ver 0. Features enabled: false Level generator options:  Level spawn location: World: (-1536,4,1332), Chunk: (at 0,0,4 in -96,83; contains blocks -1536,0,1328 to -1521,255,1343), Region: (-3,2; contains chunks -96,64 to -65,95, blocks -1536,0,1024 to -1025,255,1535) Level time: 57168 game time, 11180 day time Level dimension: 0 Level storage version: 0x00000 - Unknown? Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false) Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false Forced entities: 35 total; [EntityMinecartChest['entity.MinecartChest.name'/67, l='MpServer', x=-1586.50, y=37.50, z=1304.50], EntitySkeleton['Skeleton'/13251, l='MpServer', x=-1587.84, y=30.00, z=1284.50], EntityBat['Bat'/13571, l='MpServer', x=-1573.48, y=31.17, z=1268.07], EntitySkeleton['Skeleton'/68, l='MpServer', x=-1596.53, y=37.00, z=1304.06], EntitySkeleton['Skeleton'/13252, l='MpServer', x=-1589.50, y=30.00, z=1283.50], EntityCreeper['Creeper'/70, l='MpServer', x=-1568.56, y=30.00, z=1270.88], EntitySpider['Spider'/71, l='MpServer', x=-1570.28, y=30.00, z=1271.22], EntityBat['Bat'/13575, l='MpServer', x=-1571.55, y=30.55, z=1282.51], EntityEnderman['Enderman'/72, l='MpServer', x=-1571.69, y=30.00, z=1268.75], EntityBat['Bat'/10122, l='MpServer', x=-1589.50, y=31.10, z=1281.88], EntityBat['Bat'/10123, l='MpServer', x=-1589.75, y=30.02, z=1272.75], EntityZombie['Zombie'/15755, l='MpServer', x=-1603.50, y=43.00, z=1275.50], EntitySkeleton['Skeleton'/7052, l='MpServer', x=-1568.50, y=30.00, z=1282.50], EntityCreeper['Creeper'/15055, l='MpServer', x=-1591.97, y=37.00, z=1302.56], EntityZombie['Zombie'/15056, l='MpServer', x=-1587.50, y=37.00, z=1304.50], EntitySkeleton['Skeleton'/13084, l='MpServer', x=-1596.50, y=26.00, z=1287.50], EntityCustomNpc['William'/93, l='MpServer', x=-1532.50, y=64.00, z=1334.50], EntityZombie['Zombie'/10845, l='MpServer', x=-1605.50, y=43.00, z=1275.50], EntityCreeper['Creeper'/10847, l='MpServer', x=-1600.69, y=43.00, z=1276.75], EntityCreeper['Creeper'/10848, l='MpServer', x=-1600.75, y=43.00, z=1275.94], EntityBat['Bat'/14368, l='MpServer', x=-1605.13, y=38.10, z=1304.41], EntitySkeleton['Skeleton'/15778, l='MpServer', x=-1588.50, y=30.00, z=1274.50], EntityZombie['Zombie'/2980, l='MpServer', x=-1596.50, y=39.00, z=1247.50], EntityBat['Bat'/4772, l='MpServer', x=-1588.16, y=40.89, z=1250.59], EntityBat['Bat'/4773, l='MpServer', x=-1588.84, y=39.70, z=1253.25], EntityZombie['Zombie'/10600, l='MpServer', x=-1598.50, y=37.00, z=1302.31], EntitySpider['Spider'/10602, l='MpServer', x=-1598.50, y=37.00, z=1303.97], EntityClientPlayerMP['Luke124816'/109, l='MpServer', x=-1526.82, y=65.62, z=1327.75], EntityBat['Bat'/48, l='MpServer', x=-1568.71, y=30.19, z=1280.54], EntitySkeleton['Skeleton'/16113, l='MpServer', x=-1568.31, y=30.00, z=1268.50], EntitySkeleton['Skeleton'/16114, l='MpServer', x=-1570.50, y=30.00, z=1272.50], EntityCreeper['Creeper'/51, l='MpServer', x=-1603.63, y=25.00, z=1297.00], EntityZombie['Zombie'/16115, l='MpServer', x=-1569.50, y=30.00, z=1272.50], EntitySpider['Spider'/16118, l='MpServer', x=-1569.88, y=30.00, z=1268.50], EntityCreeper['Creeper'/60, l='MpServer', x=-1589.22, y=35.00, z=1258.78]] Retry entities: 0 total; [] Server brand: fml,forge Server type: Integrated singleplayer serverStacktrace: at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373) at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444) at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919) at net.minecraft.client.main.Main.main(SourceFile:148) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at info.mineshafter.GameStarter.main(GameStarter.java:33)
-- System Details --Details: Minecraft Version: 1.7.10 Operating System: Windows 10 (amd64) version 10.0 Java Version: 1.8.0_121, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 359120000 bytes (342 MB) / 782237696 bytes (746 MB) up to 1029177344 bytes (981 MB) JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -Xmn128M AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0 FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 6 mods loaded, 6 mods active States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored UCHIJAAAA mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)  UCHIJAAAA FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar)  UCHIJAAAA Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar)  UCHIJAAAA lightsabers{1.1.1} [Advanced Lightsabers Mod] (AdvancedLightsabers-1.7.10-1.1.1.jar)  UCHIJAAAA customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(19jun17).jar)  UCHIJAAAA starwarsmod{1.3.3} [Parzi's Star Wars Mod] (Parzi's Star Wars Mod v1.3.3.jar)  GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer: 'Intel(R) HD Graphics 530' Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10 LWJGL: 2.9.1 OpenGL: Intel(R) HD Graphics 530 GL version 4.4.0 - Build 21.20.16.4550, Intel GL Caps: Using GL 1.3 multitexturing.Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.Anisotropic filtering is supported and maximum anisotropy is 16.Shaders are available because OpenGL 2.1 is supported.
Is Modded: Definitely; Client brand changed to 'fml,forge' Type: Client (map_client.txt) Resource Packs: [CustomFaithful1.11.2] Current Language: English (US) Profiler Position: N/A (disabled) Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used Anisotropic Filtering: Off (1)

**Comment by FiskFille** [comment]
Fixed in 1.2.2
