### ISSUE TITLE
Ticking Screen Error  when trying to join my forge server

### ISSUE THREAD

**Issue by Amarrian** [FiskFille/AdvancedLightsabers#38]
---- Minecraft Crash Report ----
// Sorry :(

Time: 12/6/17 6:27 PM
Description: Ticking screen

java.lang.NullPointerException: Ticking screen
	at net.minecraft.item.ItemStack.func_77964_b(Unknown Source)
	at forestry.arboriculture.items.ItemBlockWood.saveToItemStack(ItemBlockWood.java:74)
	at forestry.arboriculture.tiles.TileWood.getPickBlock(TileWood.java:97)
	at binnie.extratrees.FakeWorld.getWooLog(FakeWorld.java:34)
	at binnie.core.genetics.TreeBreedingSystem.calculateArrays(TreeBreedingSystem.java:151)
	at binnie.core.genetics.ManagerGenetics.refreshData(ManagerGenetics.java:150)
	at binnie.core.genetics.ManagerGenetics.onWorldLoad(ManagerGenetics.java:144)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_95_ManagerGenetics_onWorldLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:61)
	at com.gildedgames.util.threadedlighting.world.ThreadedWorld.<init>(ThreadedWorld.java:56)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(Unknown Source)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_77964_b(Unknown Source)
	at forestry.arboriculture.items.ItemBlockWood.saveToItemStack(ItemBlockWood.java:74)
	at forestry.arboriculture.tiles.TileWood.getPickBlock(TileWood.java:97)
	at binnie.extratrees.FakeWorld.getWooLog(FakeWorld.java:34)
	at binnie.core.genetics.TreeBreedingSystem.calculateArrays(TreeBreedingSystem.java:151)
	at binnie.core.genetics.ManagerGenetics.refreshData(ManagerGenetics.java:150)
	at binnie.core.genetics.ManagerGenetics.onWorldLoad(ManagerGenetics.java:144)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_95_ManagerGenetics_onWorldLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:61)
	at com.gildedgames.util.threadedlighting.world.ThreadedWorld.<init>(ThreadedWorld.java:56)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(Unknown Source)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.multiplayer.GuiConnecting
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 378547584 bytes (361 MB) / 771751936 bytes (736 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJA	gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (gilded-games-util-1.7.10-1.9.jar) 
	UCHIJA	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar) 
	UCHIJA	extendedWorkbench{1.2.0.6} [Extended Workbench] ([1.7.10]ExtendedWorkbench v1.2.0.6.jar) 
	UCHIJA	aether{1.7.10-1.6} [Aether II] (aether-1.7.10-1.6.jar) 
	UCHIJA	Aquaculture{1.2.6} [Aquaculture] (Aquaculture-Mod-1.7.10.jar) 
	UCHIJA	ExtrabiomesXL{3.16.RC1} [ExtrabiomesXL] (ExtrabiomesXL-universal-1.7.10-3.16.RC1.jar) 
	UCHIJA	Forestry{4.2.1.48} [Forestry for Minecraft] (forestry_1.7.10-4.2.1.48.jar) 
	UCHIJA	BinnieCore{2.0.22.7} [Binnie Core] (binnie-mods-1.7.10-2.0.22.7.jar) 
	UCHIJA	Botany{2.0.22.7} [Botany] (binnie-mods-1.7.10-2.0.22.7.jar) 
	UCHIJA	ExtraTrees{2.0.22.7} [Extra Trees] (binnie-mods-1.7.10-2.0.22.7.jar) 
	UCHIJA	Genetics{2.0.22.7} [Genetics] (binnie-mods-1.7.10-2.0.22.7.jar) 
	UCHIJA	ExtraBees{2.0.22.7} [Extra Bees] (binnie-mods-1.7.10-2.0.22.7.jar) 
	UCHIJA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(21feb16).jar) 
	UCHIJA	deconstruction{2.2.7} [The Deconstruction Mod] (Deconstruction-Table-Mod-1.7.10.jar) 
	UCHIJA	ElementalCreepers{4.2.1} [Elemental Creepers] (Elemental Creepers-universal_1.7.10-4.2.1.jar) 
	UCHIJA	exoticbirds{1.0} [Exotic Birds] (Exotic-Birds-Mod-1.7.10.jar) 
	UCHIJA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (HarvestCraft-Mod-1.7.10.jar) 
	UCHIJA	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
	UCHIJA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (Mine-Blade-Battlegear-2-Mod-1.7.10.jar) 
	UCHIJA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJA	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) 
	UCHIJA	ExtraTiC{1.4.6} [ExtraTiC] (ExtraTiC-1.7.10-1.4.6.jar) 
	UCHIJA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJA	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJA	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJA	IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) 
	UCHIJA	lootbags{2.0.17} [Loot Bags] (LootBags-Mod-1.7.10.jar) 
	UCHIJA	MoreFurnaces{1.3.9} [More Furnaces] (MoreFurnaces-1.3.9-MC1.7.10.jar) 
	UCHIJA	plantmegapack{4.18} [Plant Mega Pack] (plantmegapack-4.18-1.7.10-1291.jar) 
	UCHIJA	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
	UCHIJA	RentServer{1.0} [§l§2Rent Server Mod] (RentServerMod.jar) 
	UCHIJA	rubymod{1.0.6} [rubymod] (RubyMod-1.4.0--For MC 1.7.10.jar) 
	UCHIJA	StorageDrawers{1.7.10-1.6.3} [Storage Drawers] (StorageDrawers-1.7.10-1.6.3.jar) 
	UCHIJA	sgs_treasure{3.0.6} [SGS Treasure!] (Treasure-3.0.6-mc1.7.10.jar) 
	UCHIJA	XaeroMinimap{1.8.5.2} [Xaero's Minimap] (Xaeros_Minimap_1.8.5.2_Forge_1.7.10.jar) 
	UCHIJA	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.1808' Renderer: 'Mobile Intel(R) 4 Series Express Chipset Family'
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: Modinstaller
	LWJGL: 2.9.1
	OpenGL: Mobile Intel(R) 4 Series Express Chipset Family GL version 2.1.0 - Build 8.15.10.1808, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because EXT_framebuffer_object is supported.
Anisotropic filtering is supported and maximum anisotropy is 2.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Amarrian** [comment]
tried render distance changing but it does not fix issue

**Comment by FiskFille** [comment]
This appears to be a Forestry crash. In fact, you don't even have Advanced Lightsabers installed.
