### ISSUE TITLE
Ticking Entity - Game Crash

### ISSUE THREAD

**Issue by cjupiter** [FiskFille/AdvancedLightsabers#43]
Okay, so every time I go into a jedi holocron, I click the first one that lets you unlock all of the other abilities, its called Force Sensitivity. Every time I left click that to unlock that it crashes my entire game and says this:

The game crashed whilst ticking entity
The game crashed whilst ticking entity
Error: java.lang.NoClassDefFoundError: scala/util/Random

Can anyone help me out and figure out what I need to do?

**Comment by cjupiter** [comment]
Heres More Details:




---- Minecraft Crash Report ----
// Shall we play a game?

Time: 7/24/18 7:21 PM
Description: Ticking entity

java.lang.NoClassDefFoundError: scala/util/Random
	at fiskfille.lightsabers.common.event.CommonEventHandler.onPlayerTick(CommonEventHandler.java:360)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_14_CommonEventHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:350)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:353)
	at net.minecraft.client.entity.EntityPlayerSP.localOnUpdate(EntityPlayerSP.java)
	at api.player.client.ClientPlayerAPI.onUpdate(Unknown Source)
	at api.player.client.ClientPlayerAPI.onUpdate(Unknown Source)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: scala.util.Random
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at fiskfille.lightsabers.common.event.CommonEventHandler.onPlayerTick(CommonEventHandler.java:360)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_14_CommonEventHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:350)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:353)
	at net.minecraft.client.entity.EntityPlayerSP.localOnUpdate(EntityPlayerSP.java)
	at api.player.client.ClientPlayerAPI.onUpdate(Unknown Source)
	at api.player.client.ClientPlayerAPI.onUpdate(Unknown Source)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityClientPlayerMP)
	Entity ID: 20
	Entity Name: Plebified
	Entity's Exact location: -163.90, 40.62, 221.31
	Entity's Block location: World: (-164,40,221), Chunk: (at 12,2,13 in -11,13; contains blocks -176,0,208 to -161,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0.00, -0.08, -0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Plebified'/20, l='MpServer', x=-163.90, y=40.62, z=221.31]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-245,92,201), Chunk: (at 11,5,9 in -16,12; contains blocks -256,0,192 to -241,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 8156982 game time, 34049 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 17 total; [EntityBat['Bat'/4, l='MpServer', x=-220.59, y=24.57, z=190.60], EntityBat['Bat'/5, l='MpServer', x=-245.46, y=26.55, z=195.09], EntityBat['Bat'/584, l='MpServer', x=-224.89, y=23.00, z=192.80], EntityBat['Bat'/367, l='MpServer', x=-212.88, y=12.57, z=248.69], EntityBat['Bat'/2192, l='MpServer', x=-199.45, y=16.18, z=270.76], EntityBat['Bat'/2193, l='MpServer', x=-204.68, y=15.86, z=274.26], EntityItem['item.item.starwarsmod.slopeWizard'/17, l='MpServer', x=-120.16, y=39.13, z=216.78], EntityBat['Bat'/2641, l='MpServer', x=-227.51, y=42.92, z=188.69], EntityBat['Bat'/1682, l='MpServer', x=-229.75, y=40.10, z=243.31], EntityVillager['Villager'/18, l='MpServer', x=-114.56, y=36.00, z=236.50], EntityBat['Bat'/2642, l='MpServer', x=-205.26, y=41.95, z=190.45], EntityBat['Bat'/2195, l='MpServer', x=-153.48, y=-18.12, z=260.11], EntityVillager['Villager'/19, l='MpServer', x=-114.69, y=39.00, z=236.31], EntityClientPlayerMP['Plebified'/20, l='MpServer', x=-163.90, y=40.62, z=221.31], EntityBat['Bat'/1528, l='MpServer', x=-142.41, y=46.10, z=247.75], EntityBat['Bat'/2200, l='MpServer', x=-235.38, y=25.00, z=232.35], EntityBat['Bat'/1660, l='MpServer', x=-227.53, y=23.90, z=218.31]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 447670456 bytes (426 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJAAAA	SmartCore{1.0.3} [Smart Core] (minecraft.jar) 
	UCHIJAAAA	lightsabers{1.1.1} [Advanced Lightsabers Mod] (AdvancedLightsabers-1.7.10-1.1.1.jar) 
	UCHIJAAAA	starwarsmod{1.3.3} [Parzi's Star Wars Mod] (Parzi's Star Wars Mod v1.3.3.jar) 
	UCHIJAAAA	SmartMoving{15.6} [Smart Moving] (SmartMoving-1.7.10-15.6.jar) 
	UCHIJAAAA	SmartRender{2.1} [Smart Render] (SmartRender-1.7.10-2.1.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.25' Renderer: 'GeForce GPU/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GPU/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.25, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [faithful64pack-v1.4.0.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by FiskFille** [comment]
Fixed (#36)
